### ISSUE TITLE
Want to render OpenCerts document in Vanilla JS

### ISSUE THREAD

**Issue by EasonC13** [Open-Attestation/decentralized-renderer-react-components#67]
Hi
I want to render the document via document renderer at Vanilla JS.

I have tried [postMessage with Actions API](https://github.com/Open-Attestation/decentralized-renderer-react-components#how-it-works) but seems it doesn't work.

Here is the code I tried.
https://gist.github.com/EasonC13/83e23b888327eee2ec7cd31919ad4053

Eventually, I hope to render the document at Vue. Users provide their `certificate.opencerts` in JSON format then the renderer shows the result.

Thank you.

**Comment by cavacado** [comment]
Hi there, I dont really know what you would like to achieve but a quick glance at your gist reveals that you are calling `window.postMessage` wrongly. Javascript doesn't have named parameters.

**Comment by EasonC13** [comment]
> Hi there, I dont really know what you would like to achieve but a quick glance at your gist reveals that you are calling `window.postMessage` wrongly. Javascript doesn't have named parameters.
> 
> In addition:
> 
> * we use penpal and penpal adds some additional messages to establish the communication.
> * we have example renderers using vue and svelte, please feel free to browse.

Hi @cavacado , Thanks for your answer.

I want to build a verifier in Vue.js like https://www.opencerts.io
(Not a render template like https://github.com/Open-Attestation/decentralized-renderer-react-template)

So far I only see template in vue, not verifier component.

I think I need to implement FrameConnector in Vanilla JS and Vue.js.
https://github.com/Open-Attestation/decentralized-renderer-react-components/blob/master/src/components/frame/FrameConnector.tsx 

Can you help me to know the sample code of how to do postMessage and let corresponding iframe render in this case?

Thank you

**Comment by Nebulis** [comment]
As mentioned above:
- we have an example using Vue: https://github.com/Open-Attestation/decentralized-renderer-vue-template
- we use https://github.com/Aaronius/penpal for the communication

If you want to handle the communication by yourself, you will have to dig in penpal
